### PR TITLE
Update libretro.h

### PR DESCRIPTION
**Pull request by zeromus**
improve retro_load_game docs to make `path` argument required.

### CODE REVIEW

**Comment by twinaphex** [comment]
Whats the reason for this?

**Comment by zeromus** [comment]
some cores crash if `path` isn't specified. i think it's because it isn't sensible for those cores to work without a path, for the reasons listed in the comments. it's essentially a requirement. The docs now say it's a requirement.

**Comment by aliaspider** [comment]
wouldn't it be better if the cores were fixed to return false instead of crashing when the path is NULL ?
I don't see the point of making the path a requirement since there are a lot of instances where there is no path to give, giving a verbose name instead of just a NULL pointer provides no benefit.

**Comment by zeromus** [comment]
Then we would need to change the documentation to say "some cores may return false from retro_load_game when data is provided but no path; try again with a fabricated path, and the core may then accept it." I think this is an awkward situation.

I assumed a frontend would generally want to make as many cores work as possible. Since several cores need some string in here, I thought a firm commandment would be best. I can rewrite it as advice, if you wish, by changing "must" to "should" and then elaborating the explanation.

**Comment by aliaspider** [comment]
why wouldn't the frontend just try the fabricated path directly if the goal is to support more cores?
what cores need the path despite reading game data from the buffer directly ? only the ones lacking heuristics to detect content type ? or are there other cases ?
the doc is already clear in that the path 'may' be null in instances where it is not possible to provide one, that implies that the path should be set in other cases.

**Comment by zeromus** [comment]
That implication was not clear, or else we wouldn't be here. My commit makes the implication explicit (and mandated). I see the sense in making it explicit (and advisory) instead. 

Without an implication (clear, or otherwise), a frontend would not have tried a fabricated path. Who would ever think you have to do that?? I was debugging through disassembly to figure that out (still easier than figuring out how to build the core and use GDB).

Nestopia was at least one core. There was another.. I can't remember. I suspect this happens because the cores are building other paths (for palettes, cheats, etc.) and when libretroizing things it was easier to leave all that intact rather than fight it.

**Comment by aliaspider** [comment]
ok, can you just add the implication to the original text instead of modifying it then ?

**Comment by aliaspider** [comment]
also, I just noticed your change to RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME. that change is wrong, the whole retro_game_info struct pointer will be set to null for no game, not the individual members.

**Comment by zeromus** [comment]
Oops. I have no excuse for that, the docs were clear.
I've committed changes to make it more advisory.

**Comment by twinaphex** [comment]
@aliaspider Do you feel comfortable with merging this or are there still issues with it?

**Comment by twinaphex** [comment]
I will assume things are fine then and merge this.

**Pull request merged**
