### PR TITLE
ibxm: updates

### PR DESCRIPTION
**Pull request by SimpleTease**
Fix Mr. Boom music playback

### CODE REVIEW

**Comment by SimpleTease** [comment]
Tracking status
https://github.com/Javanaise/mrboom-libretro/issues/36

**Comment by SimpleTease** [comment]
Requesting priority consideration for merge.

@frranck is gearing up for another Mr. Boom release before year's end, but it requires PR to be approved. Then a git pull on libretro-common can be done and checks on audio quality can be started.

This patch should fix choppy music on Windows, Linux, Mac, Android. Retroarch frontend has same ibxm patch already integrated and is working correctly.

**Comment by twinaphex** [comment]
I will be on this tomorrow.

**Comment by twinaphex** [comment]
I'm horribly sorry this took so long. Consider it merged now.

**Pull request merged**
